### ISSUE TITLE
Awake no longer functions and erroneously reports as "on" when changing pages.

### ISSUE THREAD

**Issue by pconklin** [pgerke/streamdeck-awake#6]
If I set Awake, they eye shows w/o the / through it.  If I open a folder, and then go back, the eye still does not have the / through it, but the PC will not stay awake, unless I turn awake off and then on again, then it will work until I open a folder again.

**Comment by pgerke** [comment]
Thanks for reporting this, I'll check it out!

**Comment by pgerke** [comment]
Could you kindly let me know which version you are using? I could not reproduce the issue with v2.1.0. 

I can however imagine how that issue could occur on earlier versions. While trying to reproduce your issue I realized that Stream Deck is actually terminating the plugin instances corresponding to buttons that not currently shown. So if you enable Awake and open a folder or go to a new page the plugin instance is terminated. When you close the folder or go back a new instance of the Awake plugin is started (and starting with v2.1.0 the previous state is restored). In consequence, you cannot enable Awake and then continue working on a new page or folder. As the plugin instance is terminated, your Awake settings will not be regarded. But this is another issue that I'll treat separately.

**Comment by pconklin** [comment]
2.1.0.  What you are describing below is exactly what I am seeing.

**Comment by pgerke** [comment]
Fixed in release v2.1.1
